# Generated by Django 5.2.6 on 2025-09-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.faculty')),
            ],
            options={
                'db_table': 'carreras',
            },
        ),
    ]
