# Generated by Django 5.2.6 on 2025-09-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_faculty_options_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.faculty'),
        ),
    ]
