# Generated by Django 5.2.6 on 2025-09-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='profesores',
        ),
    ]
