# Generated by Django 5.2.6 on 2025-09-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_alter_teacher_options_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='docentes',
        ),
    ]
