# Generated by Django 5.2.6 on 2025-09-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='infrastructure.student'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='infrastructure.materia'),
        ),
    ]
