# Generated by Django 5.2.6 on 2025-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_projectstate_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('es_lider', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.student')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='infrastructure.proyecto')),
            ],
            options={
                'db_table': 'proyectos_miembros',
                'managed': True,
            },
        ),
    ]
