from .user_model import User
from .role_model import Role
from .auditoria_model import Auditoria
from .faculty_model import Faculty
from .career_model import Career
from .student_model import Student
from .teacher_model import Teacher
from .materia_model import Materia
from .inscription_model import Inscription
from .project_state_model import ProjectState
from .project_model import Proyecto
from .project_member_model import ProyectoMiembro